version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: react
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: backend
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app
    databs:
      image: mongo:4.4.10 
      restart: always
      container_name: databs
      ports:
        - "27018:27018"
      environment:
        MONGO_INITDB_DATABASE: pdb
      volumes:
        - databs:/data/db
      networks: 
        - network


volumes: 
    databs:
    name: databs

networks: 
  network:
    name: network
    driver: bridge